server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 8520
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
    #采样值介于0-1之间，1则表示全部采集
    probability: 1


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.nuc.springcloud.entities

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://iniyimi:85208520@localhost:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true
#    Eureka客户端向服务端发送心跳的时间间隔，单位是秒（默认30秒）
    lease-renewal-interval-in-seconds:  1
#    Eureka服务端在收到最后一次心跳后等待时间上限，单位是秒默认（默认是90秒）超时剔除服务
    lease-expiration-duration-in-seconds:  2
